{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import numpy as np\n",
    "import plotly.graph_objects as go\n",
    "\n",
    "# ----------------- CONFIGURACIÓN GENERAL -----------------\n",
    "st.set_page_config(\n",
    "    page_title=\"Movimiento Armónico Simple - Física II\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "st.title(\"Desafío de Programación - Movimiento Armónico Simple (MAS)\")\n",
    "st.markdown(\"\"\"\n",
    "Aplicación interactiva para explorar el Movimiento Armónico Simple (MAS)\n",
    "y sus variantes: masa–resorte, péndulo simple, efecto de parámetros\n",
    "y MAS amortiguado.\n",
    "\"\"\")\n",
    "\n",
    "# Menú lateral\n",
    "seccion = st.sidebar.selectbox(\n",
    "    \"Selecciona la simulación\",\n",
    "    [\n",
    "        \"1) MAS masa–resorte\",\n",
    "        \"2) Péndulo simple\",\n",
    "        \"3) Análisis de periodo vs k y m\",\n",
    "        \"4) MAS amortiguado (caso extendido)\"\n",
    "    ]\n",
    ")\n",
    "\n",
    "# Tiempo común\n",
    "st.sidebar.markdown(\"### Parámetros de simulación\")\n",
    "t_max = st.sidebar.slider(\"Tiempo máximo [s]\", 5.0, 60.0, 20.0, 1.0)\n",
    "n_puntos = st.sidebar.slider(\"Número de puntos\", 200, 2000, 1000, 100)\n",
    "t = np.linspace(0, t_max, n_puntos)\n",
    "\n",
    "# ----------------- 1) MAS MASA-RESORTE -----------------\n",
    "if seccion.startswith(\"1\"):\n",
    "    st.subheader(\"1) Sistema masa–resorte (horizontal / vertical)\")\n",
    "\n",
    "    col1, col2 = st.columns(2)\n",
    "    with col1:\n",
    "        orientacion = st.radio(\"Orientación\", [\"Horizontal\", \"Vertical\"])\n",
    "        k = st.slider(\"Constante elástica k [N/m]\", 10.0, 500.0, 100.0, 10.0)\n",
    "        m = st.slider(\"Masa m [kg]\", 0.1, 10.0, 1.0, 0.1)\n",
    "        A = st.slider(\"Amplitud A [m]\", 0.01, 1.0, 0.2, 0.01)\n",
    "    with col2:\n",
    "        fase = st.slider(\"Fase inicial φ [rad]\", 0.0, 2*np.pi, 0.0, 0.1)\n",
    "        x0_label = \"Posición inicial desde el equilibrio\" if orientacion == \"Vertical\" else \"Posición inicial\"\n",
    "        st.write(f\"*Nota:* Para MAS ideal, la ecuación es la misma en ambas orientaciones, solo cambia el equilibrio.\")\n",
    "        # Frecuencia angular\n",
    "        omega = np.sqrt(k / m)\n",
    "\n",
    "    # Solución analítica MAS ideal\n",
    "    x = A * np.cos(omega * t + fase)\n",
    "    v = -A * omega * np.sin(omega * t + fase)\n",
    "    a = -omega**2 * x\n",
    "    Ek = 0.5 * m * v**2\n",
    "    Ep = 0.5 * k * x**2\n",
    "    Et = Ek + Ep\n",
    "\n",
    "    # Gráfica posición, velocidad, aceleración\n",
    "    fig1 = go.Figure()\n",
    "    fig1.add_scatter(x=t, y=x, name=\"Posición x(t) [m]\")\n",
    "    fig1.add_scatter(x=t, y=v, name=\"Velocidad v(t) [m/s]\")\n",
    "    fig1.add_scatter(x=t, y=a, name=\"Aceleración a(t) [m/s²]\")\n",
    "    fig1.update_layout(\n",
    "        xaxis_title=\"Tiempo [s]\",\n",
    "        yaxis_title=\"Magnitud\",\n",
    "        title=\"Posición, velocidad y aceleración en función del tiempo\"\n",
    "    )\n",
    "    st.plotly_chart(fig1, use_container_width=True)\n",
    "\n",
    "    # Gráfica energías\n",
    "    fig2 = go.Figure()\n",
    "    fig2.add_scatter(x=t, y=Ek, name=\"Energía cinética Ek\")\n",
    "    fig2.add_scatter(x=t, y=Ep, name=\"Energía potencial Ep\")\n",
    "    fig2.add_scatter(x=t, y=Et, name=\"Energía total Et\")\n",
    "    fig2.update_layout(\n",
    "        xaxis_title=\"Tiempo [s]\",\n",
    "        yaxis_title=\"Energía [J]\",\n",
    "        title=\"Energías en el MAS\"\n",
    "    )\n",
    "    st.plotly_chart(fig2, use_container_width=True)\n",
    "\n",
    "    st.markdown(\"\"\"\n",
    "    *Explicación física (resumen)*  \n",
    "    En un sistema masa–resorte ideal, la fuerza restauradora es \\(F = -kx\\),\n",
    "    lo que conduce a la ecuación diferencial:\n",
    "    \\[\n",
    "        m \\ddot{x} + kx = 0 \\quad \\Rightarrow \\quad\n",
    "        x(t) = A \\cos(\\omega t + \\varphi), \\quad \\omega = \\sqrt{k/m}\n",
    "    \\]\n",
    "    La energía total \\(E_T = E_k + E_p\\) se conserva y oscila entre cinética\n",
    "    y potencial, manteniéndose constante en el tiempo en ausencia de rozamiento.\n",
    "    \"\"\")\n",
    "\n",
    "# ----------------- 2) PÉNDULO SIMPLE -----------------\n",
    "elif seccion.startswith(\"2\"):\n",
    "    st.subheader(\"2) Péndulo simple: modelo lineal vs no lineal\")\n",
    "\n",
    "    col1, col2 = st.columns(2)\n",
    "    with col1:\n",
    "        L = st.slider(\"Longitud L [m]\", 0.1, 5.0, 1.0, 0.1)\n",
    "        g = st.slider(\"Gravedad g [m/s²]\", 1.0, 15.0, 9.81, 0.1)\n",
    "    with col2:\n",
    "        theta0_deg = st.slider(\"Ángulo inicial θ₀ [°]\", 1.0, 90.0, 20.0, 1.0)\n",
    "        theta0 = np.deg2rad(theta0_deg)\n",
    "        omega0 = 0.0  # velocidad angular inicial\n",
    "\n",
    "    # Frecuencia angular lineal\n",
    "    omega_lin = np.sqrt(g / L)\n",
    "\n",
    "    # Solución lineal: θ_lin(t)\n",
    "    theta_lin = theta0 * np.cos(omega_lin * t)\n",
    "\n",
    "    # Solución no lineal numérica (Euler simple)\n",
    "    theta = np.zeros_like(t)\n",
    "    omega = np.zeros_like(t)\n",
    "    theta[0] = theta0\n",
    "    omega[0] = omega0\n",
    "    dt = t[1] - t[0]\n",
    "\n",
    "    for i in range(len(t) - 1):\n",
    "        # Ecuación no lineal: θ'' + (g/L) sin θ = 0\n",
    "        alpha = -(g / L) * np.sin(theta[i])\n",
    "        omega[i + 1] = omega[i] + alpha * dt\n",
    "        theta[i + 1] = theta[i] + omega[i + 1] * dt\n",
    "\n",
    "    fig = go.Figure()\n",
    "    fig.add_scatter(x=t, y=np.rad2deg(theta_lin), name=\"Modelo lineal (pequeños ángulos)\")\n",
    "    fig.add_scatter(x=t, y=np.rad2deg(theta), name=\"Modelo no lineal (numérico)\")\n",
    "    fig.update_layout(\n",
    "        xaxis_title=\"Tiempo [s]\",\n",
    "        yaxis_title=\"Ángulo θ [°]\",\n",
    "        title=\"Comparación: péndulo lineal vs no lineal\"\n",
    "    )\n",
    "    st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "    st.markdown(f\"\"\"\n",
    "    *Período aproximado modelo lineal:*\n",
    "    \\[\n",
    "        T_{{lin}} = 2\\pi \\sqrt{{\\\\frac{{L}}{{g}}}} \\approx {2*np.pi*np.sqrt(L/g):.2f} \\ \\text{{s}}\n",
    "    \\]\n",
    "\n",
    "    *Comentario físico*  \n",
    "    - Para ángulos pequeños (≈ hasta 10–15°), el modelo lineal \\( \\sin\\theta \\approx \\theta \\)\n",
    "      es una muy buena aproximación.  \n",
    "    - Para ángulos grandes (\\(θ_0 = {theta0_deg:.1f}°\\)), el período real aumenta y la\n",
    "      solución no lineal se separa de la lineal.\n",
    "    \"\"\")\n",
    "\n",
    "# ----------------- 3) ANÁLISIS DE PERIODO VS K Y M -----------------\n",
    "elif seccion.startswith(\"3\"):\n",
    "    st.subheader(\"3) Análisis del efecto de k y m en el periodo\")\n",
    "\n",
    "    modo = st.radio(\"¿Qué quieres analizar?\", [\"Variar k (m fija)\", \"Variar m (k fija)\"])\n",
    "\n",
    "    if modo == \"Variar k (m fija)\":\n",
    "        m_fija = st.slider(\"Masa fija m [kg]\", 0.1, 10.0, 1.0, 0.1)\n",
    "        k_min, k_max = st.slider(\"Rango de k [N/m]\", 10.0, 1000.0, (50.0, 500.0), 10.0)\n",
    "        k_vals = np.linspace(k_min, k_max, 100)\n",
    "        T_vals = 2 * np.pi * np.sqrt(m_fija / k_vals)\n",
    "\n",
    "        fig = go.Figure()\n",
    "        fig.add_scatter(x=k_vals, y=T_vals, name=\"Periodo T(k)\")\n",
    "        fig.update_layout(\n",
    "            xaxis_title=\"k [N/m]\",\n",
    "            yaxis_title=\"Periodo T [s]\",\n",
    "            title=\"Dependencia del periodo con la constante elástica k\"\n",
    "        )\n",
    "        st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "        st.markdown(\"\"\"\n",
    "        *Conclusión:*  \n",
    "        A mayor constante elástica \\(k\\), el periodo disminuye. Es decir,\n",
    "        un resorte más \"duro\" oscila más rápido para una misma masa.\n",
    "        \"\"\")\n",
    "\n",
    "    else:\n",
    "        k_fija = st.slider(\"Constante fija k [N/m]\", 10.0, 1000.0, 100.0, 10.0)\n",
    "        m_min, m_max = st.slider(\"Rango de m [kg]\", 0.1, 20.0, (0.5, 10.0), 0.1)\n",
    "        m_vals = np.linspace(m_min, m_max, 100)\n",
    "        T_vals = 2 * np.pi * np.sqrt(m_vals / k_fija)\n",
    "\n",
    "        fig = go.Figure()\n",
    "        fig.add_scatter(x=m_vals, y=T_vals, name=\"Periodo T(m)\")\n",
    "        fig.update_layout(\n",
    "            xaxis_title=\"m [kg]\",\n",
    "            yaxis_title=\"Periodo T [s]\",\n",
    "            title=\"Dependencia del periodo con la masa m\"\n",
    "        )\n",
    "        st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "        st.markdown(\"\"\"\n",
    "        *Conclusión:*  \n",
    "        A mayor masa \\(m\\), el periodo aumenta. Un sistema más \"pesado\"\n",
    "        oscila más lentamente para un mismo resorte.\n",
    "        \"\"\")\n",
    "\n",
    "    st.markdown(\"\"\"\n",
    "    Recordemos que para el MAS ideal:\n",
    "    \\[\n",
    "        T = 2\\pi \\sqrt{\\\\frac{m}{k}}\n",
    "    \\]\n",
    "    Esta ecuación muestra explícitamente cómo influyen \\(m\\) y \\(k\\) en el periodo.\n",
    "    \"\"\")\n",
    "\n",
    "# ----------------- 4) MAS AMORTIGUADO -----------------\n",
    "elif seccion.startswith(\"4\"):\n",
    "    st.subheader(\"4) MAS amortiguado (caso extendido)\")\n",
    "\n",
    "    col1, col2 = st.columns(2)\n",
    "    with col1:\n",
    "        k = st.slider(\"Constante elástica k [N/m]\", 10.0, 500.0, 100.0, 10.0)\n",
    "        m = st.slider(\"Masa m [kg]\", 0.1, 10.0, 1.0, 0.1)\n",
    "        A = st.slider(\"Amplitud inicial A [m]\", 0.01, 1.0, 0.2, 0.01)\n",
    "    with col2:\n",
    "        zeta = st.slider(\"Factor de amortiguamiento ζ\", 0.0, 2.0, 0.2, 0.05)\n",
    "        st.write(\"ζ < 1: subamortiguado, ζ = 1: críticamente amortiguado, ζ > 1: sobreamortiguado\")\n",
    "\n",
    "    omega0 = np.sqrt(k / m)\n",
    "    x = np.zeros_like(t)\n",
    "    v = np.zeros_like(t)\n",
    "    x[0] = A\n",
    "    v[0] = 0.0\n",
    "    dt = t[1] - t[0]\n",
    "\n",
    "    # Integración numérica simple: x'' + 2ζω0 x' + ω0² x = 0\n",
    "    for i in range(len(t) - 1):\n",
    "        acc = -2 * zeta * omega0 * v[i] - omega0**2 * x[i]\n",
    "        v[i + 1] = v[i] + acc * dt\n",
    "        x[i + 1] = x[i] + v[i + 1] * dt\n",
    "\n",
    "    fig = go.Figure()\n",
    "    fig.add_scatter(x=t, y=x, name=\"x(t) amortiguado\")\n",
    "    fig.update_layout(\n",
    "        xaxis_title=\"Tiempo [s]\",\n",
    "        yaxis_title=\"Desplazamiento x [m]\",\n",
    "        title=\"Movimiento Armónico Simple Amortiguado\"\n",
    "    )\n",
    "    st.plotly_chart(fig, use_container_width=True)"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
